### ISSUE TITLE
Should import pipeline be moved to a separate project?

### ISSUE THREAD

**Issue by mbelmadani** [PavlidisLab/ndb#39]
There's no reason why the pipeline should be part of the web application. A case could be made to take the pipeline out and include it as a git submodule. Benefits include:
-Generalize importing variants into a similar schema for any project.
-Less confusion over configuration files  (See #37 about db configs)
-Cleaner commit history for main application.

**Comment by JacobsonMT** [comment]
I could see some benefits from modularizing the import pipeline. I'm not, however, convinced it should be git submodules. An alternative would be managing it as a dependency through maven (similar to basecode or gsec). What are the benefits/drawbacks of submodules vs maven?

**Comment by mbelmadani** [comment]
I don't think there's much benefits/drawbacks either way, since both repositories are accessible and owned by us. The pipeline and the application don't really talk to each other, so nothing bad would happen if one chooses to install the application but not the pipeline. Someone might want to do that; if we have the pipeline installed in one location and we want to clone a different instance of the web application (but not the pipeline), then that's easy to handle with git submodules. Submodules can also point to specific commits in case we want to guarantee that the two projects are on compatible versions.  

If it's easy to  do these things with maven (optionally installing the pipeline as an add-on and version freezing) then maybe it's better to have only maven and not maven AND submodules, to keep things simpler.

**Comment by mbelmadani** [comment]
Keeping the pipeline and application in the same repository doesn't cause any issues. Closing this for now.
